site:
  title: MicroStream Reference Manual
  url: https://manual.docs.microstream.one
  robots: allow
content:
  sources:
  - url: https://github.com/microstream-one/microstream.git
    branches: master
    start_path: docs/manual
asciidoc:
  attributes:
    page-pagination: ''
    source-language: asciidoc@
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
 