name: Antora Site with Lunr Search

on:
  workflow_dispatch:

jobs:
  antora:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Antora Site with Lunr Search
      uses: ghost-420/antora-lunr-site-action@v1.0
      with:
        antora_playbook: antora-playbook.yml
        site_sources_path: ""
      env:
        GIT_CREDENTIALS: ${{secrets.GIT_CREDENTIALS}}
