name: Antora Site with Lunr Search

on:
  workflow_dispatch:

jobs:
  antora:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{secrets.GIT_CREDENTIALS}}    
    - name: Antora Site with Lunr Search
      uses: ghost-420/antora-lunr-site-action@v1.0
      with:
        antora_playbook: antora-playbook.yml
        site_sources_path: ""
      env:
        GIT_CREDENTIALS: ${{secrets.GIT_CREDENTIALS}}
    - name: Push git subdirectory as branch
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: site
        FOLDER: site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
